### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nullpo-head/WSL-Hello-sudo#37]
Sorry for the noobie question, I'm new to Linux. I downloaded using 

    wget http://github.com/nullpo-head/WSL-Hello-sudo/releases/latest/download/release.tar.gz

after installing, can I delete the 'release ' directory that the download created? (i.e. did the install script place the required stuff elsewhere on the system so this install folder is no longer needed?)

thank you in advance!

**Comment by nullpo-head** [comment]
Hi! Thanks for trying WSL-Hello-sudo! Yeah, you can remove it. It's not necessary anymore

**Comment by YouveGotMeowxy** [comment]
ty!
