### ISSUE TITLE
Multiple distros?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nullpo-head/WSL-Hello-sudo#38]
I got this working with Ubuntu and love it, TY!

My next question is, I also have Kali installed, and ran the same exact setup [instructions](https://www.windowscentral.com/making-windows-subsystem-linux-wsl-even-better-windows-hello), but while it works in Ubuntu, it gets ignored in my Kali install. Do I have to do something different to have it work in both at the same time?

**Comment by fernandoperezlara** [comment]
Hello, It's working for other distros, I installed on my WSL2 Fedora and it's working, just changed the path of /lib/security to /lib64/security (if you didn't have problems with the installation it's not necessary) and follow this https://github.com/nullpo-head/WSL-Hello-sudo#manual-configuration (this is very important)

**Comment by YouveGotMeowxy** [comment]
@FernandoPerezLara Thant worked, TYSM!

adding `auth sufficient pam_wsl_hello.so` did the trick.

now my `/etc/pam.d/sudo` for Kali Linux looks like this, and tested and working for both Kali and Ubuntu WSL2 at the same time. :D 

```
$ cat /etc/pam.d/sudo
#%PAM-1.0

# Set up user limits from /etc/security/limits.conf.
auth       sufficient pam_wsl_hello.so
session    required   pam_limits.so

@include common-auth
@include common-account
@include common-session-noninteractive
```
