### ISSUE TITLE
install.sh doesn't work on arch

### ISSUE THREAD

**Issue by RedBeard0531** [nullpo-head/WSL-Hello-sudo#5]
install.sh assumes that things are in /lib/x86_64-linux-gnu, but arch has all of those paths directly under /lib. Changing the paths made it work, but the script should handle that automatically.

**Comment by nullpo-head** [comment]
Yeah, now WSL has other distribution than Ubuntu. at least it will be better to show some warning if the script can't find /lib/x86_64-linux-gnu directory in an environment. Thanks.

**Comment by bcr-ch** [comment]
@RedBeard0531 I have this same issue.  How were you able to work around it?  

I changed the path to match what Arch uses and it built / installed no problem.  I just now can't figure out the syntax of the /etc/pam.d/sudo file as it is quite different from Ubuntu.  (new to Arch here).

Thnx

B.

**Comment by agc93** [comment]
To add another case: install scripts also don't work in Fedora WSL. Seems like `/lib/x86_64-linux-gnu` is pretty specific to the Debian variants.
