### ISSUE TITLE
Doesn't work on WSL1 Ubuntu 20.04

### ISSUE THREAD

**Issue by piotrmocko** [nullpo-head/WSL-Hello-sudo#6]
It works on my Ubuntu 16.04 and 18.04, but it doesn't work on 20.04. 

I have installed and configured WSL Hello on my Ubuntu 20.04 several times starting with a clean distro each time. Unfortunately, it prompts for the password. I tried to debug with `su`, but it prompts for the password too and doesn't output any errors.

Microsoft Windows [Version 10.0.18363.815]

**Comment by qwqVictor** [comment]
Same problem on Windows 10 1909 and Ubuntu 20.04 LTS on WSL 1.

**Comment by handa-kenta** [comment]
Same problem on Windows 10 2004(build 19628.1) / Ubuntu 20.04 LTS / WSL2

**Comment by piotrmocko** [comment]
There is a fix waiting to merge and to release https://github.com/nullpo-head/WSL-Hello-sudo/pull/7

**Comment by nullpo-head** [comment]
Thanks, so much. I'll take a look at it. Actually, I've updated my WSL to WSL 2 and having the same problem. Thanks!

**Comment by thelastlin** [comment]
Tested PR#7 on Ubuntu 20.04 on WSL2. Works fine.
![image](https://user-images.githubusercontent.com/20792851/83258217-77a4e000-a1e8-11ea-862c-20dc4945a10e.png)

**Comment by nullpo-head** [comment]
I've release v1.1.0, which runs Ubuntu 20.04 on WSL 2. It should work in WSL 1, too. Thanks a lot, all!

**Comment by piotrmocko** [comment]
v1.2.0 works on Ubuntu 20.04 WSL 1 on Windows 10 1909
